spring:
  application:
    name: order-service
  config:
    import: configserver:http://localhost:8888

user:
  service:
    url: http://user-service
product:
  service:
    url: http://product-service