server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SwapnilBVaidya/microservices-template-springboot
          search-paths: config-repo
          default-label: master